name: Build Release APK

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - uses: gradle/actions/setup-gradle@v3

      - name: package
        run: ./gradlew assembleRelease

      - uses: ilharp/sign-android-release@v1 # Or use @nightly
        name: Sign app APK
        id: sign_app
        with:
          releaseDir: composeApp/build/outputs/apk/release
          signingKey: ${{ secrets.KEY_STORE_BASE64 }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyAlias: ${{ secrets.ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 34.0.0

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-apks
          path: ${{steps.sign_app.outputs.signedFile}}
          if-no-files-found: error
          retention-days: 20

      - name: Upload Mapping
        uses: actions/upload-artifact@v4
        with:
          name: mapping.txt
          path: composeApp/build/outputs/mapping/release/mapping.txt
          if-no-files-found: error
          retention-days: 20